### ISSUE TITLE
Restaurant Details Page

### ISSUE THREAD

**Issue by ramitfwrk** [futureworktechnologies2/Ahmed-Restaurant-project#30]
Ability to view detailed information about a caterer:
Cuisines served
Caterer name
Caterer Image
Categories of the service
Business Hours
Visual Indicators for (Admin driven):
      - Promoted
      - Instant Booking
      - Verified
      - Requires Insurance on the catering plates and serving equipment
Indicator if caterer does auto acceptance
Lead Time of the caterer
Caterer Address (Only after Booking Confirmation)
Caterer Contact Number (Only after Booking Confirmation)

**Comment by simerjit-fwrk** [comment]
Design Issues are pending yet.
