### ISSUE TITLE
Adding items to cart

### ISSUE THREAD

**Issue by ramitfwrk** [futureworktechnologies2/Ahmed-Restaurant-project#33]
Ability to add an item to the cart by selecting the number of units of that item
User should be able to view the total price of the selected items based on number of units of item selected by the user before adding an item
For any items in which minimum and maximum number of units are defined, user can only select number of units within that range
Ability to get a confirmation message when an item is added to the cart
It is not required for the user to be signed in for adding an item to the cart
User should not be able to add an item to the cart if the lead time of the item is more than than the time selected by the user for the event - User would be shown a message about this saying that The time required for preparation of this dish is more than the time left for your event. Please select other items or modify the time of the event to add this item
Items of a single caterer can be added to the cart at a single time. An order can only be contain items from a single caterer

**Comment by simerjit-fwrk** [comment]
1. Ability to add an item to the cart by selecting the number of units of that item: **DONE**
2. User should be able to view the total price of the selected items based on number of units of item selected by the user before adding an item: **DONE**
3. For any items in which minimum and maximum number of units are defined, user can only select number of units within that range: **DONE**
4. Ability to get a confirmation message when an item is added to the cart: **DONE**
5. It is not required for the user to be signed in for adding an item to the cart:  **DONE**
6. User should not be able to add an item to the cart if the lead time of the item is more than than the time selected by the user for the event - User would be shown a message about this saying that The time required for preparation of this dish is more than the time left for your event. Please select other items or modify the time of the event to add this item: **WILL BE DONE IN EVENT MILESTONE**
7. Items of a single caterer can be added to the cart at a single time. An order can only be contain items from a single caterer: **DONE**
